/*
 * Timer Actions
 */
export const TimerActions = {
  POMODORO: 'POMODORO',
  SHOR_BREAK: 'SHORT_BREAK',
  LONG_BREAK: 'LONG_BREAK',
  START_POMODORO: 'HOME_START_POMODORO',
  START_SHORT_BREAK: 'HOME_START_SHORT_BREAK',
  START_LONG_BREAK: 'HOME_START_LONG_BREAK',
  STOP_TIMER: 'HOME_STOP_TIMER',
  FINISH_TIMER: 'HOME_FINISH_TIMER',
  INCREMENT_TIMER: 'HOME_INCREMENT_TIMER'
}
